;; use K&R c style, except with 2-space indent
(defun my-c-mode-hook ()
;;  (setq c-default-style "k&r")
  (setq c-basic-offset          2)
  (c-set-offset 'arglist-intro '+)
  (c-set-offset 'arglist-cont  0 )
  (c-set-offset 'arglist-close 0 )
  (c-set-offset 'case-label    '+)
  (c-set-offset 'defun-close   0 )
  (set-variable 'c-label-minimum-indentation    0)
  (define-key c-mode-base-map [?\C-c ?c] 'uncomment-region)
  (gtags-mode                   1)
  (global-set-key (kbd "C-c C-g") 'compile)
  (local-set-key (kbd "RET") 'newline-and-indent)
  (setq          fci-rule-width 1)
  (setq fci-rule-color "dark grey")
;;  (fci-mode 1)
  (gtags-mode                   1)
)
(add-hook 'c-mode-hook 'my-c-mode-hook)
