#!/usr/bin/env bash

set -e

thisdir=$(cd $(dirname $0) && pwd -P)
workdir=$(mktemp -d)
image=mycodex-image

USER=$(whoami)
USER_ID=$(id -u)
GROUP_ID=$(id -g)

cat << EOF > ${workdir}/Dockerfile
FROM ubuntu:24.04

# Create a user with same
# permissions as host user
RUN groupadd -g ${GROUP_ID} ${USER}
RUN useradd -l -u ${USER_ID} -g ${USER} ${USER}
RUN install -d -m 0755 -o ${USER} -g ${USER} /home/${USER}

# Install codex and basic utilities
RUN apt update -y
RUN apt install -y sudo nodejs npm git ripgrep build-essential bubblewrap
RUN npm i -g @openai/codex

USER ${USER}
EOF

cat ${workdir}/Dockerfile

docker build -t ${image}:latest -f ${workdir}/Dockerfile ${workdir}

rm -r ${workdir}
