#!/usr/bin/env bash

set -e

thisdir=$(cd $(dirname $0) && pwd -P)
workdir=$(pwd)
image=mycodex-image

if [ "$#" -eq 1 ]; then
    args=()
else
    args="$@"
fi

# check for codex updates, rebuild
# image if a new version is available
installed=$(docker run ${image}:latest codex --version)
installed=$(echo ${installed} | cut -d ' ' -f 2)
available=$(docker run ${image}:latest npm view @openai/codex version)

if [ ${installed} != ${available} ];  then
  echo "New version of codex is available - rebuilding image...."
  ${thisdir}/build
fi

# You need to install codex on host and run it
# once and log in, so that the ~/.codex/
# directory is populated with authentication
# information.

echo "Running codex on ${workdir}"

docker run -it                      \
 -v ${workdir}:/home/paulmc/project \
 -v ~/.codex/:/home/paulmc/.codex/  \
 --workdir=/home/paulmc/project     \
 --network=host                     \
 ${image}:latest                    \
 codex --dangerously-bypass-approvals-and-sandbox ${args[@]}
